#ifndef IDS_H
#define IDS_H

#define ID_CHELL 0
#define ID_BLOQUE_ROCA 1
#define ID_DISPARO 2
#define ID_BLOQUE_METAL 3
#define ID_PORTAL_AZUL 4 
#define ID_PORTAL_NARANJA 5
#define ID_BOTON_APAGADO 6
#define ID_COMPUERTA 7
#define ID_ROCA 8
#define ID_EMISORARRIBA 9
#define ID_EMISORDERECHA 10
#define ID_EMISORABAJO 11
#define ID_EMISORIZQUIERDA 12
#define ID_BOLAENERGIA 13
#define ID_BOTON_PRENDIDO 14
#define ID_COMPUERTA_ABIERTA 15
#define ID_COMPUERTA_CERRADA 16
#define ID_COMPUERTA_ABRIENDO 17
#define ID_BLOQUE_DIAGONAL_0 18
#define ID_BLOQUE_DIAGONAL_90 19
#define ID_BLOQUE_DIAGONAL_180 20
#define ID_BLOQUE_DIAGONAL_270 21
#define ID_RECEPTORARRIBA_DESACTIVADO 22
#define ID_RECEPTORARRIBA_ACTIVADO 23
#define ID_RECEPTORDERECHA_DESACTIVADO 24
#define ID_RECEPTORDERECHA_ACTIVADO 25
#define ID_RECEPTORABAJO_DESACTIVADO 26
#define ID_RECEPTORABAJO_ACTIVADO 27
#define ID_RECEPTORIZQUIERDA_DESACTIVADO 28
#define ID_RECEPTORIZQUIERDA_ACTIVADO 29
#define ID_ACIDO 30
#define ID_BARRAENERGIA 31
#define ID_SPAWNPOINT 99
#define ID_AND 100
#define ID_OR 101


#endif //IDS_H
